# Generated by Django 4.0.3 on 2022-04-01 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendnotification',
            name='send_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
