# Generated by Django 4.0.3 on 2022-04-01 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_notification', '0002_sendnotification_send_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendnotification',
            name='send_date',
        ),
    ]
