# Generated by Django 4.0.3 on 2022-04-06 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('send_notification', '0004_remove_sendnotification_send_notification_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendnotification',
            name='send_notification_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
