# Generated by Django 4.0.3 on 2022-03-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_paper', '0002_alter_feedback_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='return_feedback',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
