# Generated by Django 4.0.3 on 2022-03-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload', '0002_alter_course_options_alter_semester_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataupload',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
