# Generated by Django 4.0.3 on 2022-04-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=225, null=True)),
                ('call_us', models.CharField(blank=True, max_length=225, null=True)),
                ('email_us', models.EmailField(blank=True, max_length=254, null=True)),
                ('open_hour', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
    ]
