# Generated by Django 4.0.3 on 2022-04-06 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload', '0004_alter_dataupload_status'),
        ('user', '0003_alter_role_options_alter_user_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_upload.course'),
        ),
        migrations.AddField(
            model_name='user',
            name='semester',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_upload.semester'),
        ),
    ]
