# Generated by Django 4.0.3 on 2022-04-07 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_image',
        ),
    ]
